-- Criação do banco de dados e uso dele
CREATE DATABASE COMPRE_COMIGO;
USE COMPRE_COMIGO;

-- TABELA MERCADO
CREATE TABLE TB_MERCADO (
  TB_MERCADO_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TB_MERCADO_NOME VARCHAR(100) NOT NULL,
  TB_MERCADO_ACESSIBILIDADES VARCHAR(100) NOT NULL,
  TB_MERCADO_UF CHAR(2) NOT NULL,
  TB_MERCADO_CIDADE VARCHAR(100) NOT NULL,
  TB_MERCADO_ENDERECO VARCHAR(100) NOT NULL,
  TB_MERCADO_NUMERO INTEGER NOT NULL
);

-- TABELA PRODUTO
CREATE TABLE TB_PRODUTO (
  TB_PRODUTO_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TB_PRODUTO_NOME VARCHAR(100) NOT NULL,
  TB_PRODUTO_IMAGEM VARCHAR(500),
  TB_PRODUTO_PRECO DECIMAL(10,2) NOT NULL,   
  TB_PRODUTO_TIPO VARCHAR(50) NOT NULL,
  TB_PRODUTO_DESC VARCHAR(150) NOT NULL,
  TB_PRODUTO_LOCAL VARCHAR(50) NOT NULL,
  TB_PRODUTO_VALIDADE DATE NOT NULL,
  TB_PRODUTO_DT_PRODUCAO DATE NOT NULL,
  TB_PRODUTO_LOTE VARCHAR(50) NOT NULL,
  TB_PRODUTO_QTD INTEGER NOT NULL,
  TB_PRODUTO_CHEIRO VARCHAR(255),   
  TB_PRODUTO_SABOR VARCHAR(255),
  TB_PRODUTO_TEXTURA VARCHAR(255),
  TB_PRODUTO_EMBALAGEM VARCHAR(255)
);

-- TABELA CLIENTE
CREATE TABLE TB_CLIENTE (
  TB_CLIENTE_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TB_CLIENTE_NOME VARCHAR(100) NOT NULL,
  TB_CLIENTE_TELEFONE VARCHAR(20) NOT NULL,   
  TB_CLIENTE_EMAIL VARCHAR(100) NOT NULL,
  TB_CLIENTE_SENHA VARCHAR(60) NOT NULL,     
  TB_CLIENTE_UF CHAR(2) NOT NULL,
  TB_CLIENTE_CIDADE VARCHAR(100) NOT NULL,
  TB_CLIENTE_ENDERECO VARCHAR(100) NOT NULL,
  TB_CLIENTE_NUMERO INTEGER NOT NULL,
  TB_CLIENTE_TIPOSANGUE CHAR(3) NOT NULL,
  TB_CLIENTE_ALERGIAS VARCHAR(100) NOT NULL
);

-- TABELA FUNCIONARIO
CREATE TABLE TB_FUNCIONARIO (
  TB_FUNCIONARIO_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TB_FUNCIONARIO_NOME VARCHAR(100) NOT NULL,
  TB_FUNCIONARIO_TELEFONE VARCHAR(20) NOT NULL,   
  TB_FUNCIONARIO_CPF VARCHAR(14) NOT NULL,       
  TB_FUNCIONARIO_EMAIL VARCHAR(100) NOT NULL,
  TB_FUNCIONARIO_SENHA VARCHAR(60) NOT NULL,      
  TB_MERCADO_ID INTEGER NOT NULL,
  FOREIGN KEY (TB_MERCADO_ID) REFERENCES TB_MERCADO(TB_MERCADO_ID)
);

-- TABELA ESTOQUE
CREATE TABLE TB_ESTOQUE (
  TB_ESTOQUE_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TB_PRODUTO_ID INTEGER NOT NULL,
  TB_PRODUTO_QTD INTEGER NOT NULL,
  FOREIGN KEY (TB_PRODUTO_ID) REFERENCES TB_PRODUTO(TB_PRODUTO_ID)
);

-- TABELA LISTA
CREATE TABLE TB_LISTA (
  TB_LISTA_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TB_LISTA_DATA DATE ,
  TB_LISTA_NOME VARCHAR(255),
  TB_CLIENTE_ID INTEGER NOT NULL,
  TB_PRODUTO_ID INTEGER,
  FOREIGN KEY (TB_CLIENTE_ID) REFERENCES TB_CLIENTE(TB_CLIENTE_ID),
  FOREIGN KEY (TB_PRODUTO_ID) REFERENCES TB_PRODUTO(TB_PRODUTO_ID)
);

SELECT * FROM TB_PRODUTO;
SELECT * FROM TB_MERCADO;
SELECT * FROM TB_LISTA;
SELECT TB_LISTA_NOME, MAX(TB_LISTA_DATA) as TB_LISTA_DATA
FROM TB_LISTA WHERE TB_CLIENTE_ID = 1
GROUP BY TB_LISTA_NOME;

INSERT INTO TB_LISTA (TB_LISTA_NOME, TB_CLIENTE_ID, TB_PRODUTO_ID) VALUES (123, 1, 1);

SELECT 
  *
FROM 
  TB_LISTA
INNER JOIN 
  TB_PRODUTO ON TB_LISTA.TB_PRODUTO_ID = TB_PRODUTO.TB_PRODUTO_ID WHERE TB_LISTA.TB_LISTA_NOME = 123;
